// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Clients.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Book
    {
        /// <summary>
        /// Initializes a new instance of the Book class.
        /// </summary>
        public Book()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Book class.
        /// </summary>
        /// <param name="type">Possible values include: 'Hardcover',
        /// 'Paperback', 'eBook'</param>
        public Book(int id, string title, string author, string type, string summary = default(string))
        {
            Id = id;
            Title = title;
            Author = author;
            Summary = summary;
            Type = type;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "title")]
        public string Title { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "author")]
        public string Author { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "summary")]
        public string Summary { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Hardcover', 'Paperback',
        /// 'eBook'
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

    }
}
