/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as Models from "./models";
import * as Mappers from "./models/mappers";
import * as operations from "./operations";
import { BookApiClientContext } from "./bookApiClientContext";

class BookApiClient extends BookApiClientContext {
  // Operation groups
  authors: operations.Authors;
  books: operations.Books;

  /**
   * Initializes a new instance of the BookApiClient class.
   * @param [options] The parameter options
   */
  constructor(options?: Models.BookApiClientOptions) {
    super(options);
    this.authors = new operations.Authors(this);
    this.books = new operations.Books(this);
  }
}

// Operation Specifications

export {
  BookApiClient,
  BookApiClientContext,
  Models as BookApiModels,
  Mappers as BookApiMappers
};
export * from "./operations";
