/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { ServiceClientOptions } from "@azure/ms-rest-js";
import * as msRest from "@azure/ms-rest-js";

/**
 * An interface representing Author.
 */
export interface Author {
  id?: number;
  name?: string;
}

/**
 * An interface representing Book.
 */
export interface Book {
  id: number;
  title: string;
  author: string;
  summary?: string;
  /**
   * Possible values include: 'Hardcover', 'Paperback', 'eBook'
   */
  type: Type;
}

/**
 * An interface representing BookApiClientOptions.
 */
export interface BookApiClientOptions extends ServiceClientOptions {
  baseUri?: string;
}

/**
 * Optional Parameters.
 */
export interface AuthorsAddAuthorOptionalParams extends msRest.RequestOptionsBase {
  body?: Author;
}

/**
 * Defines values for Type.
 * Possible values include: 'Hardcover', 'Paperback', 'eBook'
 * @readonly
 * @enum {string}
 */
export enum Type {
  Hardcover = 'Hardcover',
  Paperback = 'Paperback',
  EBook = 'eBook',
}

/**
 * Contains response data for the getAll operation.
 */
export type AuthorsGetAllResponse = Array<Author> & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Author[];
    };
};

/**
 * Contains response data for the addAuthor operation.
 */
export type AuthorsAddAuthorResponse = Author & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Author;
    };
};

/**
 * Contains response data for the get operation.
 */
export type AuthorsGetResponse = Author & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Author;
    };
};

/**
 * Contains response data for the get operation.
 */
export type BooksGetResponse = Array<Book> & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Book[];
    };
};
